### ISSUE TITLE
Is it possible to use openapi-backend for proxy

### ISSUE THREAD

**Issue by geka-evk** [openapistack/openapi-backend#729]
Assume I have OpenAPI yaml with bunch of endpoints, and I need to implement a proxy server, which will validate incoming requests, and then proxy them to one of other servers (let's call them - `backend servers`) for actual processing. All `backend servers` follow the same OpenAPI spec (as well as `proxy`). `Proxy` has a list of all `backend servers`, and chose one of them to proxy each request based on some info from incoming request.

The problem I see now is at this:
```
api.register({
  getPets: (c, req, res) => res.status(200).json({ result: "ok" }),
  getPetById: (c, req, res) => res.status(200).json({ result: "ok" }),
  // ....
  notFound: (c, req, res) => res.status(404).json({ err: "not found" }),
  validationFail: (c, req, res) =>
    res.status(400).json({ err: c.validation.errors }),
});
```
I don't have a list of all `operationId`s  (as `getPets` and `getPetById`), and I don't want to specify them manually. Logic for any `operationIds` on proxy is the same: just define one of `backend servers`, and pass request to it.  

And one more question: is it possible to read yaml separately (say, using `fs.readFileSync('open-api.yml', 'utf8')`, and pass its content to _OpenAPIBackend_ constructor (instead of `definition` filed as file path)

I appreciate any help/idead/suggestions

**Comment by anttiviljami** [comment]
OpenAPI Backend will default to the `notImplementedHandler` if no operation handler is specified for the request. You can use that as your catch all to proxy requests. 

And yes, you absolutely can pass the openapi definition as an object to the OpenAPIBackend constructor, instead of as a file path ✅

**Comment by geka-evk** [comment]
@anttiviljami, I think, I have an issue following your advice  :( 
![image](https://github.com/openapistack/openapi-backend/assets/16463615/34512a42-ffd7-4cbe-b572-45ad17ed802c)

So I have a OpenAPI yaml, where I have lots of endpoints definitions, each with its own `operationId`. Here's how I instantiated OpenAPIBackend:
```
  const api = new OpenAPIBackend({
    definition: API_SPEC_PATH,
    handlers: {
      validationFail: async (context, req: Hapi.Request, h: Hapi.ResponseToolkit) =>
        h.response({ err: context.validation.errors }).code(400),
      notFound: async (context, req: Hapi.Request, h: Hapi.ResponseToolkit) =>
        h.response({ err: 'Not found' }).code(404),
      notImplementedHandler: async (c, req, h: Hapi.ResponseToolkit) => {
        return h.response({ err: 'notImplemented' }).code(502);
      },
    },
  });
```
And I was hoping that each time call existing endpoint, my `notImplementedHandler` will be called, and I got 502 error.
But I always get 500 error:
```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}
```
and code execution never gets to `notImplementedHandler`

Am I doing something wrong?
